services:
  - type: web
    name: inventory-management-system
    env: java
    plan: free
    region: frankfurt
    branch: master
    buildCommand: "./gradlew bootJar"
    startCommand: "java -jar build/libs/Inventory-Management-System-0.0.1-SNAPSHOT.jar"
    disks:
      - name: inventory-data
        mountPath: /data
        sizeGB: 1
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:/data/inventory-db