services:
  - type: web
    name: inventory-app
    env: docker
    plan: free
    region: frankfurt
    branch: master
    buildCommand: "./gradlew bootBuildImage"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: inventory-db
    plan: free